name: Seeking the Source
favicon: null
layout_spectrum: 0.23174842540174723
typography_spectrum: 0.30046456190757453
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3722603744827211
  lightness: 0.8117886844556779
  saturation: 0.5469617194030434
  rhythmicContrast: 0.7551577631384134
purpose: []
